apiVersion: v1
data:
  # 配置dockder镜像仓库的用户名密码，.dockerconfigjson 的内容用下面命令生成
  # echo -n '{"auths":{"https://registry.xxx/":{"username":"admin","password":"ne7y346WmAt8Xk","auth":"YWRtaW46bmU3eTM0NldtQXQ4WGs="}}}' | base64 -i -
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5Lmhhb2thaXhpbi53aW4vIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6Im5lN3kzNDZXbUF0OFhrIiwiYXV0aCI6IllXUnRhVzQ2Ym1VM2VUTTBObGR0UVhRNFdHcz0ifX19
kind: Secret
metadata:
  name: webapp-template
  namespace: webapp-template
type: kubernetes.io/dockerconfigjson
